default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: 12345
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: react_rails
  user: postgres
  password: 12345

test:
  <<: *default
  database: react_rails
  user: postgres
  password: 12345

production:
  <<: *default
  database: react_rails
  username: postgres
  password: <%= ENV["12345"] %>
